import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import './globals.css'
import 'bootstrap/dist/css/bootstrap.min.css';
import Header from '@/components/UI/app.header';
import Footer from '@/components/UI/app.footer';

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Bunney Store',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
  isAdmin = false,
}: {
  children: React.ReactNode,
  isAdmin?: boolean;
}) {
  
  return (
    <html lang="en">
      <body className={inter.className}>
      {!isAdmin&&(
        <Header/>
      )}
        <div style={{marginTop:'7rem',marginLeft:'3rem'}}>
          {children}
        </div>
        {!isAdmin&&(
          <Footer/>
        )}
      </body>
    </html>
  )
}
